config/routes.rb
Rpg::Application.routes.draw do
  
  resources :characters do
    resources :abilities
  end
  devise_for :users

  root 'welcome#index'

  

end

app/models/ability.rb
class Ability < ActiveRecord::Base
  belongs_to :character

  validates :name,
            :presence => true,
            :length => { :minimum => 3 }

  validates :level,
            :presence => true,
            :numericality => {
              :greater_then => 0,
              :less_than_or_equal_to => 100
            }

  def red?
    self.level <= 30
  end

  def yellow?
    self.level > 30 && self.level <= 70
  end

  def green?
    self.level > 70
  end
end

app/models/character.rb
class Character < ActiveRecord::Base
  belongs_to :user
  has_many :abilities, :dependent => :destroy
  validates :name, presence: true,
    length: { minimum: 3 }
  mount_uploader :avatar, AvatarUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :characters, :dependent => :destroy
end

app/controllers/abilities_controller.rb
class AbilitiesController < ApplicationController
  def new
    @character = Character.find(params[:character_id])
    @ability = @character.abilities.build
  end

  def edit
    @character = Character.find(params[:character_id])
    @ability = Ability.find(params[:id])
  end

  def create
    @character = Character.find(params[:character_id])
    @ability = @character.abilities.build(allowed_params)

    if @ability.save
      redirect_to character_path(@character)
    else
      render 'new'
    end
  end

  def update
    @character = Character.find(params[:character_id])
    @ability = Ability.find(params[:id])

    if @ability.update(allowed_params)
      redirect_to @character
    else
      render 'edit'
    end
  end

  def destroy
    @character = Character.find(params[:character_id])
    @ability = Ability.find(params[:id])
    @ability.destroy

    redirect_to @character
  end


  private
  def allowed_params
    params.require(:ability).permit(:name, :level)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:username, :email, :password, :remember_me) }
  end
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  # There are public, private and protected methods in Ruby,
  # but only public methods can be actions for controllers.
  def index
    @characters = Character.all    
  end

  def show
    @character = Character.find(params[:id])
  end

  def new
    @character = current_user.characters.build
  end

  def edit
    @character = Character.find(params[:id])
  end

  def create
    @character = current_user.characters.build(character_params)

    if @character.save
      redirect_to character_path(@character)
    else
      render 'new'
    end
  end

  def update
    @character = Character.find(params[:id])

    if @character.update(character_params)
      redirect_to character_path(@character)
    else
      render 'edit'
    end
  end

  def destroy
    @character = Character.find(params[:id])
    @character.destroy

    redirect_to characters_path 
  end

  private
  def character_params
    params.require(:character).permit(:name, :avatar)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/abilities_helper.rb
module AbilitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/abilities/_form.html.erb
<%= form_for([@character, @ability]) do |f| %>
  <p>
  <%= f.label :name %><br>
  <%= f.text_field :name %>
  </p>

  <p>
  <%= f.label :level %><br>
  <%= f.text_field :level %>
  </p>

  <p>
  <%= f.submit %>
  </p>
<% end %> 

app/views/abilities/edit.html.erb
<h1>Editing ability</h1>

<%= render 'form' %>

<%= link_to 'Back', characters_path %>

app/views/abilities/new.html.erb
<h1>New ability</h1>

<%= render 'form' %>

<%= link_to 'Back', characters_path %>

app/views/characters/_form.html.erb
   <%= form_for @character do |f| %>
    <p>
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </p>
 
    <p>
      <%= f.label :avatar %><br>
      <%= f.file_field :avatar %>
    </p>
 
    <p>
      <%= f.submit %>
    </p>
  <% end %>  
 

app/views/characters/_index.html.erb
<h1>Listing characters</h1>
<% if current_user.characters.present? %>
  <table>
  <tr>
    <th>Name</th>
    <th>Avatar</th>
    <th colspan="2"></th>
  </tr>

  <% @characters.each do |character| %>
    <tr>
      <td><%= character.name %></td>
      <td><%= character.avatar %></td>
      <td><%= link_to 'Show', character_path(character) %></td>
      <td><%= link_to 'Edit', edit_character_path(character) %></td>
      <td><%= link_to 'Destroy', character_path(character),
        method: :delete,
        data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </table>

<% else %>
    <p>You do not own any characters... <%= link_to 'Create one :)', new_character_path %></p>
<% end %>

  <%= link_to 'New character', new_character_path %>
  <%= link_to 'Back', root_path %>

app/views/characters/edit.html.erb
<h1>Editing character</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', characters_path %>

app/views/characters/index.html.erb
<%=  render 'index'  %>

app/views/characters/new.html.erb
<h1>New character</h1>

<%= render 'form' %>
 
<%= link_to 'Back', characters_path %>

app/views/characters/show.html.erb
<% if @character.user_id == current_user.id %>
  <h1>
    <strong>Name:</strong>
    <%= @character.name %>
  </h1>

  <p>
  <strong>Avatar:</strong>
  <%= image_tag(@character.avatar_url, :width => 300) if @character.avatar.present? %>
  </p>


  <h2> Abilities:</h2>
  <table>
    <tr>
      <th>Name</th>
      <th>Level</th>
      <th colspan="2"></th>
    </tr>

    <% @character.abilities.each do |ability| %>
      <tr>
      <td><%= ability.name %></td>
      <td><%= ability.level %></td>      
      <td><%= link_to 'Edit ability', edit_character_ability_path(ability.character, ability) %></td>
      <td><%= link_to 'Destroy ability', character_ability_path(ability.character, ability),
        method: :delete,
        data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </table>

  <%= link_to 'Add ability', new_character_ability_path(@character) %>
  <%= link_to 'Edit', edit_character_path(@character) %> |
  <%= link_to 'Back', characters_path %>

<% else %>
  <%= render 'index' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rpg</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">The Mini RPG Editor app</a>
    </div>
    <p class="navbar-text navbar-right">
	<% if user_signed_in? %>
 		Logged in as <strong><%= current_user.email %></strong>.
  		<%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
 		<%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
	<% else %>
  		<%= link_to "Register", new_user_registration_path, :class => 'navbar-link'  %> |
  		<%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
	<% end %>
  </div>
</nav>

<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<div class="container">
  <%= yield %>
</div>

<footer>
  <div class="container">
    <a href="https://github.com/mimimalizam/minirpgeditor">Milana+Check something</a> 2015
  </div>
</footer>
</body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome</h1>
<% if user_signed_in? %>
 	<%= link_to 'My characters', controller: 'characters' %>
	<%= link_to 'New character', new_character_path %>
<% end %>